Repository apache-superset/superset-ui-plugins-deckgl, pull requests merged in 2021-08, with the labels that each got.

#35 Fix issue with large timestamp arrays
  packages/superset-ui-legacy-preset-chart-deckgl/src/CategoricalDeckGLContainer.jsx
  packages/superset-ui-legacy-preset-chart-deckgl/src/utils/time.js
Labels: size/XS

#39 docs: add instructions for npm release
  README.md
Labels: size/S

#40 chore: fill descriptions and rearrange tags
  packages/superset-ui-legacy-preset-chart-deckgl/src/Multi/index.js
  packages/superset-ui-legacy-preset-chart-deckgl/src/layers/Arc/index.js
  packages/superset-ui-legacy-preset-chart-deckgl/src/layers/Geojson/index.js
  packages/superset-ui-legacy-preset-chart-deckgl/src/layers/Grid/index.js
  packages/superset-ui-legacy-preset-chart-deckgl/src/layers/Hex/index.js
  packages/superset-ui-legacy-preset-chart-deckgl/src/layers/Path/index.js
  packages/superset-ui-legacy-preset-chart-deckgl/src/layers/Polygon/index.js
  packages/superset-ui-legacy-preset-chart-deckgl/src/layers/Scatter/index.js
  packages/superset-ui-legacy-preset-chart-deckgl/src/layers/Screengrid/index.js
Labels: size/M

#41 chore: bump deckgl and mapbox libs
  packages/superset-ui-legacy-preset-chart-deckgl/package.json
  packages/superset-ui-legacy-preset-chart-deckgl/yarn.lock
Labels: size/XXL

#42 fix(hex): restore control panel to functioning state
  packages/superset-ui-legacy-preset-chart-deckgl/src/layers/Hex/controlPanel.js
Labels: size/M

#43 fix(scatter): fix legend and labels
  packages/superset-ui-legacy-preset-chart-deckgl/src/CategoricalDeckGLContainer.jsx
  packages/superset-ui-legacy-preset-chart-deckgl/src/components/Legend.jsx
  packages/superset-ui-legacy-preset-chart-deckgl/src/factory.jsx
  packages/superset-ui-legacy-preset-chart-deckgl/src/layers/Scatter/Scatter.jsx
  packages/superset-ui-legacy-preset-chart-deckgl/src/layers/Scatter/controlPanel.js
  packages/superset-ui-legacy-preset-chart-deckgl/src/transformProps.js
Labels: size/M

#45 chore: version bump
  package.json
  yarn.lock
Labels: size/M

#46 chore: bump superset-ui peer dependencies
  packages/superset-ui-legacy-preset-chart-deckgl/package.json
Labels: size/XS
